name: build
on: push
jobs:
  build:
    name: First-Job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14, 16]
    steps:
    - name: First Step
      env:
        MY_VAR: Hello World! Hi There?
        FIRST_NAME: Sudhar
        LAST_NAME: Balaji
      run:
        echo $MY_VAR $FIRST_NAME $LAST_NAME.
    - name: Second Step
      if: success()
      run: echo "Reporting - Previous Job has completed Successfully.!!"
    - name: Third Step
      uses: actions/checkout@v1
      with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
